export default {
  ADD_EXPENSE: 'ADD_EXPENSE',
  REMOVE_EXPENSE: 'REMOVE_EXPENSE',
  EDIT_EXPENSE: 'EDIT_EXPENSE',
  SET_FILTERS_TEXT: 'SET_FILTERS_TEXT',
  SET_FILTERS_SORT: 'SET_FILTERS_SORT',
  SET_FILTERS_DATE: 'SET_FILTERS_DATE',
  SET_EXPENSES: 'SET_EXPENSES',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT'
};